services:
  api:
    build: .
    container_name: racing_api
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: ankane/pgvector:latest
    container_name: racing_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"

volumes:
  postgres_data:
